### ISSUE TITLE
报错信息

### ISSUE THREAD

**Issue by systemime** [HunterXuan/WebQATest#2]
`(base) C:\Users\Work Hard\Desktop\02--WebQATest-master\WebQATest-master>python Test.py
[Q]:世界上平均海拔最高的大洲是五大洲中的哪个?
[A]:南极洲大陆平均海拔近几千米，是地球上平均海拔最高的大洲。
----------
[Q]:明朝时波斯指哪里？
[A]:波斯这个词已被用了数个世纪，主要是西方，用来指明南伊朗的一片地区从前以“persis”和“parsa”闻名
----------
[Q]:因豪赌欠千万被追债的内地影帝是谁?
[A]:有传闻讲，大陆光头影帝葛优，一年来经常出入澳门赌场豪赌，前后输掉上千万，但事后失踪避债
----------
[Q]:《老人与海》是美国哪位著名小说家的作品?
[A]:《老人与海》是海明威于1951年在古巴写的一篇中篇小说，于1952年出版。
----------
[Q]:杨修之死的作者是?
[A]:杨修之死节选自《三国演义》第七十二回作者:元末明初小说家罗贯中
----------
[Q]:圣经故事中传说可以让世界上各种陆上生物躲避一场大洪水的大船叫什么?
[A]:方舟遗址诺亚方舟的故事出自《圣经》，传说是这一个方形船只，其建造的目的是为了让诺亚与他的家人，以及世界上的各种陆上生物能够躲避一场上帝因故而造的大洪水灾难。
----------
[Q]:宇宙的"宇"字表示的是时间还是空间?
[A]:宇宙是代表空间和时间,宇是空间,宙是空间.那么空间(是宇宙)是由那几个元素组成呢,古希腊的亚里士多德曾经说是由水、火、土、气组成,但是现在已近发现了100多种元素,但是他说的是大概.宇宙是形成大爆炸,而大爆炸前是什么景象,我想没人知道.那个...
----------
[Q]:中国哪位皇帝最长寿？
[A]:中国历史上,从秦始至清亡,总共有36位皇帝超过60岁,12位皇帝超过70岁,其中6人超过80岁,最长寿的当属乾隆89岁.清高宗弘历89岁,在位60年,3年太上皇.自称"千古第一完帝"梁武帝萧衍86岁,在位48年,在南朝的皇帝中列第一位.唐女皇武则天82岁,在位15...
----------
[Q]:我国古代称为"启明星"的是太阳系八大行星的什么星?
[A]:启明，即启明星，也就是太阳系八大行星之一的金星。
----------
[Q]:电视剧《网球王子》演龙马的人是谁
[A]:越前龙马龙马秦俊杰（在《满城尽带黄金甲》中饰演小王子那位）1.姓名：秦俊杰2.年龄173.生日：1991/09/014：身高：177体重：1205：喜欢的颜色有哪些：白色浅蓝色6：最崇拜的人：金城武周杰伦尼古拉斯凯奇李俊基7:最喜欢的歌曲有...
----------
Traceback (most recent call last):
  File "Test.py", line 7, in <module>
    service.get_top_answers('杨利伟是谁？')
  File "C:\Users\Work Hard\Desktop\02--WebQATest-master\WebQATest-master\service.py", line 38, in get_top_answers
    aids = get_best_answer_id(question)
  File "C:\Users\Work Hard\Desktop\02--WebQATest-master\WebQATest-master\service.py", line 67, in get_best_answer_id
    test_data = data_helpers.get_test_data()
  File "C:\Users\Work Hard\Desktop\02--WebQATest-master\WebQATest-master\data_helpers.py", line 38, in get_test_data
    test = json.load(open('.\data\test.json'))
OSError: [Errno 22] Invalid argument: '.\\data\test.json'

(base) C:\Users\Work Hard\Desktop\02--WebQATest-master\WebQATest-master>python Test.py
[Q]:你是第几人称
[A]:推荐答案‘我’是第一人称；‘你’是第二人称；‘他’是第三人称
----------
[Q]:太阳大气的最外层是
[A]:日冕是太阳大气的最外层,由高温、低密度的等离子体所组成
----------
[Q]:黄山属于哪个省
[A]:推荐答案黄山，中国5a级旅游景区、国家级风景名胜区、首批全国文明风景旅游区示范点，是中国最美的、令人震撼的十大名山之一，在“中华十大名山”排名中居第四位，位于安徽省南部黄山市境内（景区由市直辖），是安徽旅游的标志
----------
[Q]:清朝哪个皇帝号玉痴
[A]:乾隆皇帝酷爱玉器，现在故宫博物院的三万件玉器，多数为他所藏，乾隆为他的儿子后来的嘉庆皇帝起名叫颙琰，琰是美玉的名字；永琰的十六个兄弟也都以玉器的名字命名，乾隆自己则被后人称为玉痴
----------
[Q]:川菜"蚂蚁上树"的主要食材是肉末炒什么?
[A]:米粉肉沫蚂蚁上树是川菜蚂蚁上树材料蚂蚁上树，又叫肉末粉丝，成菜肉香四溢、粉丝绵软入味，由于吃时肉末会粘在粉丝上，犹如蚂蚁上树一般，此名便由之而来
----------
[Q]:著名戏剧演员红线女是什么戏剧演员
[A]:严凤英--黄梅戏大师.红线女--粤剧大师.申凤梅--河南越调大师
----------
[Q]:二泉映月是谁写的
[A]:二泉映月是阿炳的代表作
----------
[Q]:《西游记》中的火焰山在哪里
[A]:《西游记》中的火焰山是吐鲁番最出名的景点，位于新疆维吾尔自治区吐鲁番盆地的北缘，古丝绸之路北道
----------
[Q]:由亚非国家组成的世界羽毛球联合会成立于哪一年？
[A]:比赛时,一人或两人为一方,中隔一网,用球拍经网上往返击球,使球落到对方的场地...1978年2月,由亚非国家组成的世界羽毛球联合 会于香港成立,同年11月举办了第1届...
----------
[Q]:谁知道炎亚纶真名
[A]:炎亚纶(1986年11月20日-)，本名吴庚霖，台湾男歌手，演员，也是台湾男子演唱团体飞轮海最年轻的成员
----------
2019-01-21 22:27:27.018790: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE instructions, but these are available on your machine and could speed up CPU computations.
2019-01-21 22:27:27.030240: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE2 instructions, but these are available on your machine and could speed up CPU computations.
2019-01-21 22:27:27.041396: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
2019-01-21 22:27:27.050384: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2019-01-21 22:27:27.063706: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2019-01-21 22:27:27.074888: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2019-01-21 22:27:27.086155: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2019-01-21 22:27:27.098294: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
input_x_1  Tensor("input_x_1:0", shape=(100, 200, 100), dtype=float32, device=/device:GPU:1)
loss  Tensor("loss/add:0", shape=(), dtype=float32, device=/device:GPU:1)
TypeError: expected bytes, NoneType found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Test.py", line 7, in <module>
    service.get_top_answers('杨利伟是谁？')
  File "C:\Users\Work Hard\Desktop\02--WebQATest-master\WebQATest-master\service.py", line 38, in get_top_answers
    aids = get_best_answer_id(question)
  File "C:\Users\Work Hard\Desktop\02--WebQATest-master\WebQATest-master\service.py", line 89, in get_best_answer_id
    saver.restore(sess, tf.train.latest_checkpoint('./runs/1525274605/checkpoints'))
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1548, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 789, in run
    run_metadata_ptr)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1139, in _do_call
    return fn(*args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1121, in _run_fn
    status, run_metadata)
SystemError: <built-in function TF_Run> returned a result with an error set`

**Comment by HunterXuan** [comment]
拉代码后，模型需要重新训练，然后根据模型保存路径，修改 [这行代码](https://github.com/HunterXuan/WebQATest/blob/master/service.py#L89)

**Comment by systemime** [comment]
十分感谢！^-^
